apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  labels:
    name: test-nginx
  namespace: coba-kubernetes
spec:
  containers:
  - name: test-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
